### ISSUE TITLE
Event Handler

### ISSUE THREAD

**Issue by EmanSza** [EmanSza/tmi-handler#11]
Event Handler is a massive issue, 
Automatic Event Handling should be added so then when tmi.js gets updated the project doesnt need to be manually done. This would also allow projects to be more scalable

**Comment by leonardobagi** [comment]
Agreed, I think I know a way to improve it

**Comment by leonardobagi** [comment]
Listening to all the events and checking which ones the user want to recieve is a bad idea since it creates a number of useless listeners

**Comment by EmanSza** [comment]
@leonardobagi If you could possibly check my fix for Branch 2.0 that would be great

**Comment by leonardobagi** [comment]
Yea thats exactly what I did in my PC lol. I will make a small refactor on loading events/commands and push it to 2.0 branch
