### ISSUE TITLE
feat: types

### ISSUE THREAD

**Issue by GmBodhi** [EmanSza/tmi-handler#6]
Add types for client-facing methods and classes.

**Comment by EmanSza** [comment]
A Community Member has added basic types and I merged them into the dev branch. please test this out and give back feedback
Note: the MessageCollector isn't perfect and it would be great if any bugs are reported and or fixed

**Comment by GmBodhi** [comment]
I've noticed that we're initiating the `Client` inside the wrapper class which is not good. We need to give enough freedom to the end-user. The first parameter to the wrapper class can be imported directly, as it's just a peer dependency.

**Comment by leonardobagi** [comment]
> The first parameter to the wrapper class can be imported directly, as it's just a peer dependency.
I've thought of that too...I'm thinking on improve my typings and also change that...

**Comment by EmanSza** [comment]
Typings should be improved with the latest Merge.
Create a new issue if you have any more suggestions

**Comment by GmBodhi** [comment]
I'm not sure why we have this
![image](https://user-images.githubusercontent.com/71921036/150632924-2e11432d-d48f-49ee-b8cb-40706a486595.png)
